#-Basic info----------------------------------------------------------------------------------------
display_name: min_read_check
name: min_read_check__v2_2_3
version:
  schema: ["v2_1_0"]
  code: "v2_2_3"
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    Checks that there's a minimum number of reads after trimming to run.
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_min_read_check
# None
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [size_check]
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  min_num_reads: 10000
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  adapters_fasta: "/bifrost/components/bifrost_min_read_check/resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      paired_reads:
          summary:
            data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    categories:
      size_check:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
  sample_component:
    summary:
      has_min_num_of_reads:  # Boolean
    results:
      min_read_check/data_yaml: {}
#---------------------------------------------------------------------------------------------------
